# Generated by Django 3.1.8 on 2022-12-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.FloatField()),
                ('b_manager', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=300)),
                ('b_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BloodCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_blood', models.CharField(max_length=3)),
                ('comp_type1', models.CharField(blank=True, max_length=3, null=True)),
                ('comp_type2', models.CharField(blank=True, max_length=3, null=True)),
                ('comp_type3', models.CharField(blank=True, max_length=3, null=True)),
                ('comp_type4', models.CharField(blank=True, max_length=3, null=True)),
                ('comp_type5', models.CharField(blank=True, max_length=3, null=True)),
                ('comp_type6', models.CharField(blank=True, max_length=3, null=True)),
                ('comp_type7', models.CharField(blank=True, max_length=3, null=True)),
                ('comp_type8', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Others', 'others')], max_length=6)),
                ('dob', models.DateField()),
                ('phoneno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('class_name', models.CharField(choices=[('csa', 'CSA'), ('csb', 'CSB'), ('eca', 'ECA'), ('ecb', 'ECB'), ('eee', 'EEE'), ('mech', 'MECH'), ('eb', 'EB')], max_length=4)),
                ('batch', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=4)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('last_donated_date', models.DateField()),
                ('diseases', models.CharField(max_length=1000)),
                ('allergies', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('cardiac', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('bleeding_disorders', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('hiv', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('hepatitis', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodcompatibility')),
            ],
        ),
    ]
