# Generated by Django 4.1.4 on 2022-12-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.districts'),
        ),
    ]
