# Generated by Django 4.1.4 on 2022-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='allergies',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bleeding_disorders',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='branch',
            field=models.CharField(choices=[('CSA', 'CSA'), ('CSB', 'CSB'), ('ECA', 'ECA'), ('ECB', 'ECB'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('EB', 'EB')], max_length=4),
        ),
        migrations.AlterField(
            model_name='donor',
            name='cardiac',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='diseases',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hepatitis',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hiv',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
    ]
